name: gated2depth
channels:
  - anaconda
  - defaults
dependencies:
  - _tflow_1100_select=0.0.1=gpu
  - absl-py=0.7.1=py36_0
  - astor=0.8.0=py36_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2019.5.15=1
  - cairo=1.14.12=h8948797_3
  - certifi=2019.6.16=py36_1
  - cudatoolkit=8.0=3
  - cudnn=7.1.3=cuda8.0_0
  - cupti=8.0.61=0
  - cycler=0.10.0=py36_0
  - dbus=1.13.6=h746ee38_0
  - expat=2.2.6=he6710b0_0
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.9.1=h8a8886c_1
  - gast=0.2.2=py36_0
  - glib=2.56.2=hd408876_0
  - graphite2=1.3.13=h23475e2_0
  - grpcio=1.16.1=py36hf8bcb03_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.4=243
  - jasper=2.0.14=h07fcdf6_1
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.1.0=py36he6710b0_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=h4deb6c0_3
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.8.0=hd408876_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - markdown=3.1.1=py36_0
  - matplotlib=3.1.1=py36h5429711_0
  - mkl=2019.4=243
  - mkl-service=2.0.2=py36h7b6447c_0
  - mkl_fft=1.0.14=py36ha843d7b_0
  - mkl_random=1.0.2=py36hd81dba3_0
  - ncurses=6.1=he6710b0_1
  - numpy=1.16.4=py36h7e9f1db_0
  - numpy-base=1.16.4=py36hde5b4d6_0
  - opencv=3.4.2=py36h6fd60c2_1
  - openssl=1.1.1=h7b6447c_0
  - pcre=8.43=he6710b0_0
  - pip=19.2.2=py36_0
  - pixman=0.38.0=h7b6447c_0
  - protobuf=3.8.0=py36he6710b0_0
  - py-opencv=3.4.2=py36hb342d67_1
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py36h05f1152_2
  - python=3.6.9=h265db76_0
  - python-dateutil=2.8.0=py36_0
  - pytz=2019.2=py_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - scipy=1.3.1=py36h7c811a0_0
  - setuptools=41.0.1=py36_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.12.0=py36_0
  - sqlite=3.29.0=h7b6447c_0
  - tensorboard=1.10.0=py36hf484d3e_0
  - tensorflow=1.10.0=gpu_py36h8dbd23f_0
  - tensorflow-base=1.10.0=gpu_py36h3435052_0
  - tensorflow-gpu=1.10.0=hf154084_0
  - termcolor=1.1.0=py36_1
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.3=py36h7b6447c_0
  - werkzeug=0.15.5=py_0
  - wheel=0.33.4=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
prefix: /scratch/fs2/grubtob/miniconda3/envs/gated2depth

